server:
  address: localhost
  port : 8141
spring:
  application:
    name: ShopME
  config:
    import: 'optional:configserver:'
  datasource:
    url: jdbc:postgresql://tuffi.db.elephantsql.com:5432/ijlawxyk
    username: ijlawxyk
    password: DsXt2xlqeC6O-VS6HeLfapKcv60maAfj
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true